export default  [
  { id: 0, year:"Spring 2023", title: "UIL One Act Play", description:"This is an amazing description", color: "LimeGreen" },
  { id: 1, year:"Spring 2023", title: "UIL One Act Play", description:"This is an amazing description", color: "Tomato" },
  { id: 2, year:"Spring 2023", title: "San Jacinto College Clinic", description:"This is an amazing description", color: "#789" },
  { id: 3, year:"Fall 2022", title: "Mamma Mia", description:"This is an amazing description", color: "Crimson" },
  { id: 4, year:"Fall 2022", title: "Mamma Mia", description:"This is an amazing description", color: "Crimson" },
  { id: 5, year:"Fall 2022", title: "Mamma Mia", description:"This is an amazing description", color: "Crimson" },
  { id: 6, year:"Fall 2022", title: "Mamma Mia", description:"This is an amazing description", color: "Crimson" },
  { id: 7, year:"Fall 2022", title: "Mamma Mia", description:"This is an amazing description", color: "#789" },
  { id: 8, year:"Fall 2022", title: "Mamma Mia", description:"This is an amazing description", color: "#789" },
  { id: 9, year:"Spring 2022", title: "Moon Over Buffalo", description:"This is an amazing description", color: "#789" },
  { id: 10, year:"Spring 2022", title: "Moon Over Buffalo", description:"This is an amazing description", color: "#789" },
  { id: 11, year:"Fall 2021", title: "Once on this Island", description:"This is an amazing description", color: "#789" },
  { id: 12, year:"Fall 2021", title: "Once on this Island", description:"This is an amazing description", color: "#789" },
  { id: 13, year:"Fall 2021", title: "Once on this Island", description:"This is an amazing description", color: "#789" },
  { id: 14, year:"Spring 2021", title: "Alice in Wonderland", description:"This is an amazing description", color: "#789" },
  { id: 15, year:"Spring 2021", title: "Alice in Wonderland", description:"This is an amazing description", color: "#789" },
  { id: 16, year:"Spring 2021", title: "Alice in Wonderland", description:"This is an amazing description", color: "#789" },
  { id: 17, year:"Spring 2021", title: "The Marriage of Bett and Boo", description:"This is an amazing description", color: "#789" },
  { id: 18, year:"Spring 2021", title: "The Marriage of Bett and Boo", description:"This is an amazing description", color: "#789" },
  { id: 19, year:"Spring 2020", title: "Blood Wedding", description:"This is an amazing description", color: "#789" },
  { id: 20, year:"Spring 2020", title: "Blood Wedding", description:"This is an amazing description", color: "#789" },
  { id: 21, year:"Fall 2019", title: "Adult Mamma Mia", description:"This is an amazing description", color: "#789" },
  { id: 22, year:"Fall 2019", title: "Is There a Comic in the House?", description:"This is an amazing description", color: "#789" },
  { id: 23, year:"Fall 2019", title: "Is There a Comic in the House?", description:"This is an amazing description", color: "#789" },
  { id: 24, year:"Fall 2019", title: "Alice in Wonderland", description:"This is an amazing description", color: "#789" },
  { id: 25, year:"Fall 2019", title: "The Miraculous Journey of Edward Tulane", description:"This is an amazing description", color: "#789" },
  { id: 26, year:"Fall 2019", title: "The Miraculous Journey of Edward Tulane", description:"This is an amazing description", color: "#789" },
];